language: node_js

node_js:
  - "0.10"
  - "4.9.1"
  - "6.17.1"
  - "8.16.0"
  - "10.16.0"

sudo: false

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - libstdc++6 # upgrade libstdc++ on linux to support C++11
